### ISSUE TITLE
Пропорции изображения в карточке

### ISSUE THREAD

**Issue by Ontarion** [Ontarion/allconcerts-web#4]
В данный момент фон карточки - изображение с LastFM. Оно квадратное, а карточки - нет.

**Comment by Ontarion** [comment]
Я посмотрю, что смогу сделать со своей стороны

cc: @seriyezh

**Comment by seriyezh** [comment]
![concertscardswithfullwidthimages](https://user-images.githubusercontent.com/7056214/36204286-bf32d434-119b-11e8-9456-b090aa92ae4f.png)
Как тебе такой вариант? Картинка выравнивается по ширине и прибивается к верху. Обрезается только низ картинки.

**Comment by Ontarion** [comment]
Супер, вот так отлично 😎 И чего это мы сразу об этом не подумали)

**Comment by seriyezh** [comment]
Закроем?

**Comment by Ontarion** [comment]
Ага
